# may not be comprehensive
# may include packages that are not actually used
# some packages may not be on CRAN and will need to be googled
# some code from packages has been edited and put into scripts in the repository

library(ape)
library(Cairo)
library(countrycode)
library(cowplot)
library(data.table)
library(dendextend)
library(devEMF)
library(doBy)
library(dplyr)
library(doParallel)
library(egg)
library(foreach)
library(ggeffects)
library(ggh4x)
library(ggnewscale)
library(ggplot2)
library(ggplotify)
library(ggpubr)
library(ggsankey) #devtools::install_github('davidsjoberg/ggsankey')
library(ggthemes)
library(glmmTMB)
library(grid)
library(gridBase)
library(gridGraphics)
library(gt)
library(gtools)
library(lavaan)
library(lme4)
library(magrittr)
library(patchwork)
library(phyloseq)
library(plsRglm)
library(reshape2)
library(rnaturalearth)
library(rnaturalearthdata)
library(rworldmap)
library(scales)
library(scatterpie)
library(see)
library(semPlot)
library(semptools)
library(semTools)
library(sf)
library(sjPlot)
library(tidySEM)
library(tidyverse)
library(viridis)
library(V.PhyloMaker2) # github
library(WorldFlora)
